// <auto-generated />
using System;
using BlazorExpenseTracker.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorExpenseTracker.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230131060431_InitialSeedData")]
    partial class InitialSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorExpenseTracker.Shared.Models.ExpenseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 10.0m,
                            CreatedAt = new DateTime(2023, 1, 31, 6, 4, 30, 918, DateTimeKind.Utc).AddTicks(4186)
                        },
                        new
                        {
                            Id = 2,
                            Amount = 100.0m,
                            CreatedAt = new DateTime(2023, 1, 31, 7, 4, 30, 918, DateTimeKind.Utc).AddTicks(4190)
                        },
                        new
                        {
                            Id = 3,
                            Amount = 0.0m,
                            CreatedAt = new DateTime(2023, 1, 31, 8, 4, 30, 918, DateTimeKind.Utc).AddTicks(4201)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
