// <auto-generated />
using System;
using BlazorExpenseTracker.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorExpenseTracker.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorExpenseTracker.Shared.Models.ExpenseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 10.0m,
                            CreatedAt = new DateTime(2023, 1, 31, 6, 18, 58, 919, DateTimeKind.Utc).AddTicks(6702),
                            Description = "",
                            Title = "Bought a Snack"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 100.0m,
                            CreatedAt = new DateTime(2023, 1, 31, 7, 18, 58, 919, DateTimeKind.Utc).AddTicks(6706),
                            Description = "",
                            Title = "Bought a phone"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 0.0m,
                            CreatedAt = new DateTime(2023, 1, 31, 8, 18, 58, 919, DateTimeKind.Utc).AddTicks(6713),
                            Description = "",
                            Title = "Bought Lunch"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
